[workspace]
members = ["rust-xlsb-writer", "rust-xlsb-core"]
resolver = "2"

[workspace.package]

version = "0.1.0"
edition = "2024"
rust-version = "1.88.0"

homepage = "https://github.com/SaelKimberly/rust-xlsb-writer"
documentation = "https://github.com/SaelKimberly/rust-xlsb-writer"
repository = "https://github.com/SaelKimberly/rust-xlsb-writer"
authors = ["SaelKimberly <sael.kimberly@yandex.ru>"]
license = "Apache-2.0"
readme = "README.md"

keywords = ["data", "xlsb", "excel", "arrow"]
categories = ["encoding"]
